DROP DATABASE IF EXISTS openmaptiles;
CREATE DATABASE openmaptiles;
CREATE USER martin PASSWORD 'MARTINPASSWORD';
GRANT ALL PRIVILEGES ON DATABASE openmaptiles TO martin;
\c openmaptiles
GRANT CREATE,USAGE ON SCHEMA public TO martin;
CREATE EXTENSION postgis;
CREATE EXTENSION hstore;
CREATE EXTENSION gzip;
\q